/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Delete;

import Dashboard.Admin;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class Deleteemp extends javax.swing.JFrame {

    /**
     * Creates new form Deleteemp
     */
    
        Connection conn=null;
        PreparedStatement pstmt=null;
        ResultSet rs = null;
        
    public Deleteemp() {
        initComponents();
        connect();
    }
    
    
    public void connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employeesystem_db", "root","");
            pstmt = conn.prepareStatement("SELECT * FROM employeedata_tb");
            rs = pstmt.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            
            DefaultTableModel dtm =(DefaultTableModel) emp_table.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Vector v = new Vector();
                for(int i = 1; i<=n; i++){
                v.add(rs.getString("Emp_id"));
                v.add(rs.getString("Name"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Department"));
                v.add(rs.getString("Gender"));
                v.add(rs.getString("FathersName"));
                v.add(rs.getString("Salary"));
                v.add(rs.getString("MobileNum"));
                v.add(rs.getString("Paddress"));
                v.add(rs.getString("Dob"));
                v.add(rs.getString("Taddress"));
                v.add(rs.getString("DOJ"));
                
                }
                    dtm.addRow(v);
                }
            
        } catch (Exception e) {
            System.out.println("error--->"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        Dashboard_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1017, 600));

        jPanel1.setBackground(new java.awt.Color(218, 228, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Delete");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(395, 395, 395))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(218, 228, 230));

        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Emp_id", "Name", "Email", "Department", "Gender", "FathersName", "Salary", "MobileNum", "Paddress", "Dob", "Taddress", "DOJ"
            }
        ));
        emp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_table);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        Dashboard_menu.setText("Back");
        Dashboard_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(Dashboard_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dashboard_menu)
                    .addComponent(deletebtn))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tableMouseClicked
        // TODO add your handling code here:
        
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        DefaultTableModel tableModel = (DefaultTableModel) emp_table.getModel();
//
//        String emp_id= tableModel.getValueAt(emp_table.getSelectedRow(),0).toString();
//        String name = tableModel.getValueAt(emp_table.getSelectedRow(),1).toString();
//        String email = tableModel.getValueAt(emp_table.getSelectedRow(),2).toString();
//        String department= tableModel.getValueAt(emp_table.getSelectedRow(),3).toString();
//        String gender = tableModel.getValueAt(emp_table.getSelectedRow(),4).toString();
//        String fathername = tableModel.getValueAt(emp_table.getSelectedRow(),5).toString();
//        String salary = tableModel.getValueAt(emp_table.getSelectedRow(),6).toString(); 
//        String mobile = tableModel.getValueAt(emp_table.getSelectedRow(),7).toString();
//        String paddress = tableModel.getValueAt(emp_table.getSelectedRow(),8).toString();
//       String dateOfBirth1 = tableModel.getValueAt(emp_table.getSelectedRow(), 9).toString();
//        String taddress = tableModel.getValueAt(emp_table.getSelectedRow(),10).toString();
//        String DOj = tableModel.getValueAt(emp_table.getSelectedRow(),11).toString();
        //        String doj = tableModel.getValueAt(emp_table.getSelectedRow(),7).toString();
        //        String salary = tableModel.getValueAt(emp_table.getSelectedRow(),8).toString();

//        emp_idtxt.setText(emp_id);
//        nametxt.setText(name);
//        emailid.setText(email);
//        salarytxt.setText(salary);
//        paddresstxt.setText(paddress);
//        mobiletxt.setText(mobile);
//        departmentcom.setSelectedItem(department);
//        mobiletxt.setText(mobile);
//        taddresstxt1.setText(taddress);
//        fatherntxt.setText(fathername);
//        
//        try {
//    // Parse the date string to a Date object
//    Date dateOfBirthDate = dateFormat.parse(dateOfBirth1);
//    dateOfBirth.setDate(dateOfBirthDate);
//    
//} catch (Exception e) {
//    e.printStackTrace();
//}
//        
//
//        if(gender.equals("male")){
//            male.setSelected(true);
//        }else if(gender.equals("Female")){
//            female.setSelected(true);
//        }else if(gender.equals("other")){
//            other.setSelected(true);
//        }

    }//GEN-LAST:event_emp_tableMouseClicked

    private void Dashboard_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_menuActionPerformed
        // TODO add your handling code here:
        Admin Db= new Admin();
        Db.setVisible(true);
        dispose();
    }//GEN-LAST:event_Dashboard_menuActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete selected row", "Delete", JOptionPane.YES_NO_OPTION );
        if(opt ==0)
        {
            try {
                DefaultTableModel tableModel = (DefaultTableModel) emp_table.getModel();
                int selectedRow = emp_table.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                    return;
                }
                String emp_id = tableModel.getValueAt(selectedRow, 0).toString();
                //            String name = nametxt.getText();
                //            String email= emailid.getText();
                //            String department = departmentcom.getSelectedItem().toString();
                //            String gender = male.isSelected()? "Male" : (female.isSelected()?"Female":"Others");
                //            String fathersname= fatherntxt.getText();
                //            String salary=salarytxt.getText();
                //            String mobile = mobiletxt.getText();
                //            String paddress = paddresstxt.getText();
                //            String taddress = taddresstxt1.getText();
                //            String dateOfBirth = dateOfBirth.getDate().toString();
                // String DOB = jDateChooser1.setDate(null);

                //            java.util.Date selectedDate = jDateChooser1.getDate();
                //            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                //            String DateOfBirth = (selectedDate != null) ? sdf.format(selectedDate) : "";

                //            java.util.Date selectedDatee = jDateChooser2.getDate();
                //            SimpleDateFormat sd= new SimpleDateFormat("yyyy-MM-dd");
                //            String DateOfJoining = (selectedDatee != null) ? sd.format(selectedDatee) : "";

                pstmt = conn.prepareStatement("DELETE from employeedata_tb where Emp_id=?");

                pstmt.setString(1, emp_id);
                //            pstmt.setString(1, name);
                //            pstmt.setString(2, email);
                //            pstmt.setString(3, department);
                //            pstmt.setString(4, gender);
                //            pstmt.setString(5, fathersname);
                //            pstmt.setString(6, salary);
                //            pstmt.setString(7, mobile);
                //            pstmt.setString(8, paddress);
                //pstmt.setString(9, DateOfBirth);
                // pstmt.setString(10, taddress);
                // pstmt.setString(11, DateOfJoining);
                //pstmt.setString(9, dateOfBirth);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "User Detail is deleted");
                    connect();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete user detail");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deleteemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deleteemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deleteemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deleteemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deleteemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard_menu;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTable emp_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
